# Generated by Django 3.1.1 on 2020-09-24 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_bids_category_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='vendor',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.auctionitem'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
