# Generated by Django 3.1.1 on 2020-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200925_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
