# Generated by Django 3.1.1 on 2020-09-25 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
