# Generated by Django 3.1.1 on 2020-09-25 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionitem_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='category',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
