# Generated by Django 3.1.1 on 2020-09-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200925_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='auctions.category'),
        ),
    ]
