# Generated by Django 3.1.1 on 2020-09-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200926_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), to='auctions.category'),
        ),
    ]
