# Generated by Django 3.1.1 on 2020-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200926_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='category', to='auctions.category'),
        ),
    ]
